runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "0d 30s"

handlers:

- url: /data
  static_dir: data
  secure: always

- url: /images
  static_dir: images
  secure: always

- url: /manifest.json
  static_files: manifest.json
  upload: manifest.json
  secure: always

- url: /(.*\.js)$
  static_files: build/\1
  upload: build/.*\.js$
  secure: always

- url: /list/.*
  static_files: index.html
  upload: index.html
  secure: always
  http_headers:
    Link:
      </shop-app.js>;rel=preload;as=script
      </shop-list.js>;rel=preload;as=script

- url: /detail/.*
  static_files: index.html
  upload: index.html
  secure: always
  http_headers:
    Link:
      </shop-app.js>;rel=preload;as=script
      </shop-detail.js>;rel=preload;as=script

- url: /cart
  static_files: index.html
  upload: index.html
  secure: always
  http_headers:
    Link:
      </shop-app.js>;rel=preload;as=script
      </shop-cart.js>;rel=preload;as=script

- url: /checkout
  static_files: index.html
  upload: index.html
  secure: always
  http_headers:
    Link:
      </shop-app.js>;rel=preload;as=script
      </shop-checkout.js>;rel=preload;as=script

- url: /.*
  static_files: index.html
  upload: index.html
  secure: always
  http_headers:
    Link:
      </shop-app.js>;rel=preload;as=script

skip_files:
- bower_components/
- node_modules/
- src/
- test/
